### ISSUE TITLE
library screening of around 20000 ligand for a single protein structure get killed andnot running on available 2 GPU

### ISSUE THREAD

**Issue by pramodkp** [gcorso/DiffDock#100]
Hi,

When running protein ligand of around 20000 complex it get killed.
When reduced ligands to 10000 it get executed.
Just to know if its limited to 10000 complex or its due to computational  performance issue.
Also I am facing a issue where 2 GPU are available but it utilize only one GPU.

regards
Pramod

**Comment by gcorso** [comment]
Hi @pramodkp 

The issue for why it gets killed is that in the current code, we are loading and storing all the preprocessed complexes in memory and this might become too much for the machine. Hopefully, this memory issue can be solved in the future (of course feel free to open pull request!) but, in the meantime, I suggest splitting it into multiple files. 

Similar for the multi-GPU issue, as I mentioned in the other issue, splitting the CSV is the best thing available with the current version of the code!

Hope this helps,
Gabriele

**Comment by pramodkp** [comment]
Is there a way to estimate how much memory is available and how much memory will be utilise by 100 complexes so that every time we  check and run complexes as per memory availability.

any python or bash command ? 

Thanks 
pramod
