### ISSUE TITLE
Can DiffDock generate gibbs free energy scores?

### ISSUE THREAD

**Issue by levinhein** [gcorso/DiffDock#105]
Hello! Thank you for developing an amazing tool. I'm trying DiffDock to verify binding of a potential drug-protein interaction. Is gibbs free energy available for DiffDock? Or maybe I missed it, may I ask where I can find it from the results? Thank you!

**Comment by gcorso** [comment]
Hi @levinhein 

No, at the moment DiffDock does not compute gibbs free energies. This will hopefully be added in future versions. 
However, we (and collaborators) have observed positive correlation between the confidence score given by DiffDock (to the first or first few poses) and the binding affinity. This correlation can be made even stronger by combining DiffDock's score with traditional docking scoring functions (e.g. Vina or GNINA).

I hope this helps!

**Comment by BJWiley233** [comment]
Could you use Boltz's affinity combined with structure and hotspots perhaps to come up with at least ballbark value for that specific pocket that a ligand get generated in?
