### ISSUE TITLE
 CUDA out of memory issue

### ISSUE THREAD

**Issue by MachineGUN001** [gcorso/DiffDock#106]
How can I set py to run on CPU instead of GPU or is there any way to skip the CUDA out of memory issue?

many thanks

**Comment by alpha-beta-user** [comment]
just change the device to cpu
`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`

**Comment by alpha-beta-user** [comment]
or you can decrease batchsize

**Comment by alpha-beta-user** [comment]
> Where do you put in that "device = torch.device......." line?

in inference.py

**Comment by MachineGUN001** [comment]
thanks for your suggestions, I'll give a try
