### ISSUE TITLE
installation issues (solved)

### ISSUE THREAD

**Issue by dan9thsense** [gcorso/DiffDock#113]
Just a note in case others run into the same issues.  I built diffdock with CUDA 11.7 installed and torch 1.13

I first tried to install using the environment.yml file in the repository.  This fails and I eventually learned why the README does not suggest doing that.  I suggest modifying the README to explicitly say not to do this unless the environment.yml file is fixed or unless your build has very specific versions of CUDA and torch.  It would save a lot of troubleshooting.

problems with the environment.yml install
```
...miniconda3/envs/diffdock/lib/python3.9/site-packages/e3nn/o3/_spherical_harmonics.py:82: 
UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. 
This is an indication that codegen Failed for some reason.
```

However, the diffdock inference program still runs– this is just a warning.  I think it does not use the GPU though.
This has been seen before in issue #43 but the solution there did not work for me.

I also encountered this error:
```
  File "/home/duerr/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```
This error is addressed deep in the thread of issue #1.  They say:

If I execute pip install -U torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu113.html in the environment it does not update anything, if I pip uninstall the packages and reinstall them then 

And it is true, doing this (modified from the answer to correspond to the installation of torch 1.13 and cuda 1.7) inside the conda diffdock environment gets rid of the error:

pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric
pip install -U torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html

I decided to start over with a new conda environment and only install the needed packages, mostly following the updated README, but now I got a sequence of errors, mostly due to version incompatabilities:

The pip installs fail with these problems:
```
streamlit 1.17.0 requires blinker>=1.0.0, which is not installed.
streamlit 1.17.0 requires importlib-metadata>=1.4, which is not installed.
nbconvert 7.2.8 requires beautifulsoup4, which is not installed.
nbconvert 7.2.8 requires importlib-metadata>=3.6; python_version < "3.10", which is not installed.
jupyter-packaging 0.12.3 requires setuptools>=60.2.0, but you have setuptools 58.2.0 which is incompatible.
```
Resolved each one by installing the specified package.

Next, get a series of errors that require uninstalling current versions and reinstalling with the versions specified in the environment.yml file:

OSError: /home/dbarry/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll

torch_scatter/_scatter_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll

pip uninstall torch_cluster
Successfully uninstalled torch-cluster-1.6.1+pt113cu117

pip install torch-cluster==1.6.0

pip uninstall torch-scatter
Successfully uninstalled torch-scatter-2.1.1+pt113cu117

pip install torch-scatter -f https://data.pyg.org/whl/torch-1.13.0+117.html
pip install torch-scatter==2.0.9

torch_sparse/_diag_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
Successfully uninstalled torch-sparse-0.6.17+pt113cu117

pip install torch-sparse==0.6.15
That pip install fails.  You have  to install from source and you have to do a recursive clone:
cd ~
git clone --recursive https://github.com/rusty1s/pytorch_sparse
cd pytorch_sparse
pip install .
Successfully installed torch-sparse-0.6.17 (Note, it still did not install 0.6.15)

And, with all that, inference runs and uses the GPU.

**Comment by pramodkp** [comment]
hi @dan9thsense 

How many GPUs it uses ?
In our case we have 2 GPUs available but it uses only first GPU.
