### ISSUE TITLE
DiffDock keeps removing Hs

### ISSUE THREAD

**Issue by maykcaldas** [gcorso/DiffDock#115]
Hello, all!

I'm amazed by DiffDock. It's a really nice tool!
But can anyone help me with an issue?

I understand that when using smiles for the ligand, all the hydrogens (Hs) are treated implicitly. But even if I provide a sdf file, it removes all the Hs.
I found a `--keep_local_structures` argument in the dev branch whose description is `Keeps the local structure when specifying an input with 3D coordinates instead of generating them with RDKit`, but even when using it, the Hs are still removed.

I also noticed that the arguments `--model_dir` and `--confidence_model_dir` take model parameters from `workdir/paper_score_model` and `workdir/paper_confidence_model`, respectively, by default. 
Changing the parameter `remove_hs` to avoid removing Hs `remove_hs: false` led me to this error:

```
/usr/local/lib/python3.10/dist-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/DiffDock/inference.py", line 108, in <module>
    model = get_model(score_model_args, device, t_to_sigma=t_to_sigma, no_parallel=True)
  File "/content/DiffDock/utils/utils.py", line 100, in get_model
    model = model_class(t_to_sigma=t_to_sigma,
  File "/content/DiffDock/models/all_atom_score_model.py", line 153, in __init__
    nn.Linear(2 * ns if not self.odd_parity else ns, ns, bias=False),
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TensorProductScoreModel' object has no attribute 'odd_parity'
```

I made sure the `all_atoms` parameter was set to true. But I can't say how those parameters are used within the code.

I made a minimal reproducible [notebook](https://colab.research.google.com/drive/1QGDSnAopei7NKsqOnDGGtHnwnlv6toGT?usp=sharing) to check this issue.

Any suggestion on how to handle this is appreciated!
Thanks!

Best,
Mayk.

**Comment by HannesStark** [comment]
Hi Mayk,

We suggest adding the Hs back in computationally to the file you obtained with a tool like openbabel, pymol, rdkit, or reduce if you really need them.

The current model weights we provide are not trained with hydrogens and using them there is no option to keep the hydrogens. One would have to retrain a model that also considers hydrogens and that is what the provided remove_hs flag is for. We tried keeping Hs but it did not help and causes compute overhead.
