### ISSUE TITLE
Documentation - Rank Number Somewhat Confusing

### ISSUE THREAD

**Issue by LRParser** [gcorso/DiffDock#117]
When evaluating the results in the `results` folder output by DiffDock, it is unclear if a user should take the `rank1` sdf file to be the best hit, or instead take the last sequentially-numbered rank to be the best hit. E.g. on my run, I see rank1 has a confidence of 1.51 and rank40 has a confidence of 5.81. Is it thus correct to consider rank40 to be the better pose? I think so, however conventionally I would have thought rank1 would be the "best" pose (e.g. 1st place). Am I understanding this correctly?

**Comment by gcorso** [comment]
Hi @LRParser, yes the top 1 hit should be the rank1. Beware that the confidence number can also be negative therefore I expect the 5.81 to be -5.81. In general confidence > 0 means high confidence of correct pose, < 0 medium or low confidence. 
I hope this helps!
