### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by KimTeakJun** [gcorso/DiffDock#119]
### utils/inference_utils.py 191 line Error
**Traceback (most recent call last):
  File "/home/agent/miniconda3/envs/diffdock/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/agent/miniconda3/envs/diffdock/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/agent/DiffDock/inference.py", line 71, in <module>
    test_dataset = InferenceDataset(out_dir=args.out_dir, complex_names=complex_name_list, protein_files=protein_path_list,
  File "/home/agent/DiffDock/utils/inference_utils.py", line 191, in __init__
    self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}chain{j}'] for j in range(len(s))])
  File "/home/agent/DiffDock/utils/inference_utils.py", line 191, in <listcomp>
    self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}chain{j}'] for j in range(len(s))])
KeyError: 'complex_0chain0'**
 
**Code 3 days ago**
`self.lm_embeddings.append([lm_embeddings[complex_names[i] + '_chain_' + str(j)] for j in range(len(s))])`
**Uploaded code:**
`self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}chain{j}'] for j in range(len(s))])`
**Maybe you need to fix code:**
`self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}_chain_{j}'] for j in range(len(s))])`

**Comment by ilkwonch** [comment]
I think the the line 191 in inference_util.py was changed from previous one and that occurs errors.
You can modify it to previous one and it would work fine. 
self.lm_embeddings.append([lm_embeddings[complex_names[i] + '_chain_' + str(j)] for j in range(len(s))])

**Comment by mainguyenanhvu** [comment]
I faced the same error. Thanks @ilkwonch, it worked when I changed the code.

**Comment by KimTeakJun** [comment]
@ilkwonch Thank you for answer

**Comment by gcorso** [comment]
Apologies for the issue, the code is now fixed (similar to what @ilkwonch suggested)!
