### ISSUE TITLE
cannot set up the environment

### ISSUE THREAD

**Issue by stzhangjie** [gcorso/DiffDock#121]
When I set up the environment, in the final step as below, the error happens. 

the final step, pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'

error message：

(diffdock_yml) zhangjie@zhangjie-OptiPlex-5080:~/7exp/DiffDock$ pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
Collecting openfold@ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
  Cloning https://github.com/aqlaboratory/openfold.git (to revision 4b41059694619831a7db195b7e0988fc4ff3a307) to /tmp/pip-install-vlqniyj9/openfold_f97a153c26fb4c1ab918c9822f7d6446
  Running command git clone --filter=blob:none --quiet https://github.com/aqlaboratory/openfold.git /tmp/pip-install-vlqniyj9/openfold_f97a153c26fb4c1ab918c9822f7d6446
  Running command git rev-parse -q --verify 'sha^4b41059694619831a7db195b7e0988fc4ff3a307'
  Running command git fetch -q https://github.com/aqlaboratory/openfold.git 4b41059694619831a7db195b7e0988fc4ff3a307
  Running command git checkout -q 4b41059694619831a7db195b7e0988fc4ff3a307
  Resolved https://github.com/aqlaboratory/openfold.git to commit 4b41059694619831a7db195b7e0988fc4ff3a307
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: openfold
  Building wheel for openfold (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [163 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/openfold
      copying openfold/config.py -> build/lib.linux-x86_64-cpython-39/openfold
      copying openfold/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold
      creating build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/residue_constants.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/protein.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      creating build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/import_weights.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/superimposition.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/callbacks.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/trace_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/lr_schedulers.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/logger.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/validation_metrics.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/argparse.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/tensor_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/loss.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/rigid_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/feats.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/checkpointing.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/suppress_output.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/seed.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/chunk_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/exponential_moving_average.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      creating build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/msa.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/structure_module.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/triangular_attention.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/heads.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/dropout.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/evoformer.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/model.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/outer_product_mean.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/pair_transition.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/template.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/embedders.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/primitives.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/torchscript.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/triangular_multiplicative_update.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      creating build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/mmcif_parsing.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/input_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/templates.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/parsers.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/feature_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/errors.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_transforms.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_modules.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      creating build/lib.linux-x86_64-cpython-39/openfold/resources
      copying openfold/resources/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/resources
      creating build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/utils.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/amber_minimize.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/cleanup.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/relax.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      creating build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      copying openfold/utils/kernel/attention_core.py -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      copying openfold/utils/kernel/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      creating build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/utils.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/kalign.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/hhblits.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/jackhmmer.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/hhsearch.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      running egg_info
      creating openfold.egg-info
      writing openfold.egg-info/PKG-INFO
      writing dependency_links to openfold.egg-info/dependency_links.txt
      writing top-level names to openfold.egg-info/top_level.txt
      writing manifest file 'openfold.egg-info/SOURCES.txt'
      reading manifest file 'openfold.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'openfold.egg-info/SOURCES.txt'
      /home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'openfold.utils.kernel.csrc' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'openfold.utils.kernel.csrc' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'openfold.utils.kernel.csrc' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'openfold.utils.kernel.csrc' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/compat.h -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda.cpp -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vlqniyj9/openfold_f97a153c26fb4c1ab918c9822f7d6446/setup.py", line 74, in <module>
          setup(
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.3). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openfold
  Running setup.py clean for openfold
Failed to build openfold
Installing collected packages: openfold
  Running setup.py install for openfold ... error
  error: subprocess-exited-with-error

  × Running setup.py install for openfold did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      running install
      /home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/openfold
      copying openfold/config.py -> build/lib.linux-x86_64-cpython-39/openfold
      copying openfold/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold
      creating build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/residue_constants.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      copying openfold/np/protein.py -> build/lib.linux-x86_64-cpython-39/openfold/np
      creating build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/import_weights.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/superimposition.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/callbacks.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/trace_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/lr_schedulers.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/logger.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/validation_metrics.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/argparse.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/tensor_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/loss.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/rigid_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/feats.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/checkpointing.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/suppress_output.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/seed.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/chunk_utils.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      copying openfold/utils/exponential_moving_average.py -> build/lib.linux-x86_64-cpython-39/openfold/utils
      creating build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/msa.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/structure_module.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/triangular_attention.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/heads.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/dropout.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/evoformer.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/model.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/outer_product_mean.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/pair_transition.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/template.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/embedders.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/primitives.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/torchscript.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      copying openfold/model/triangular_multiplicative_update.py -> build/lib.linux-x86_64-cpython-39/openfold/model
      creating build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/mmcif_parsing.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/input_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/templates.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/parsers.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/feature_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/errors.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_transforms.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_pipeline.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      copying openfold/data/data_modules.py -> build/lib.linux-x86_64-cpython-39/openfold/data
      creating build/lib.linux-x86_64-cpython-39/openfold/resources
      copying openfold/resources/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/resources
      creating build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/utils.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/amber_minimize.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/cleanup.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      copying openfold/np/relax/relax.py -> build/lib.linux-x86_64-cpython-39/openfold/np/relax
      creating build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      copying openfold/utils/kernel/attention_core.py -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      copying openfold/utils/kernel/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel
      creating build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/utils.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/kalign.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/__init__.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/hhblits.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/jackhmmer.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      copying openfold/data/tools/hhsearch.py -> build/lib.linux-x86_64-cpython-39/openfold/data/tools
      running egg_info
      writing openfold.egg-info/PKG-INFO
      writing dependency_links to openfold.egg-info/dependency_links.txt
      writing top-level names to openfold.egg-info/top_level.txt
      reading manifest file 'openfold.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'openfold.egg-info/SOURCES.txt'
      /home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'openfold.utils.kernel.csrc' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'openfold.utils.kernel.csrc' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'openfold.utils.kernel.csrc' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'openfold.utils.kernel.csrc' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/compat.h -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda.cpp -> build/lib.linux-x86_64-cpython-39/openfold/utils/kernel/csrc
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vlqniyj9/openfold_f97a153c26fb4c1ab918c9822f7d6446/setup.py", line 74, in <module>
          setup(
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 692, in run
          self.run_command('build')
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "/home/zhangjie/anaconda3/envs/diffdock_yml/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.3). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> openfold

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

--------

And this is my CUDA version:
hint: See above for output from the failure.
(diffdock_yml) zhangjie@zhangjie-OptiPlex-5080:~/7exp/DiffDock$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-lightning         2.0.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torch-cluster             1.6.1+pt113cu117          pypi_0    pypi
torch-geometric           2.1.0.post1              pypi_0    pypi
torch-scatter             2.1.1+pt113cu117          pypi_0    pypi
torch-sparse              0.6.17+pt113cu117          pypi_0    pypi
torch-spline-conv         1.2.2+pt113cu117          pypi_0    pypi
torchaudio                0.12.1               py39_cu113    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.13.1               py39_cu113    pytorch

**Comment by evancollins1** [comment]
Any update on this? I am having a similar problem.
