### ISSUE TITLE
KeyError: '1a0qchain0'

### ISSUE THREAD

**Issue by shuhaozhinsitro** [gcorso/DiffDock#124]
**I tried to run the example shown in README and I keep receiving _KeyError: '1a0qchain0'_:**

**Command I used:**

python -m inference.py --protein_sequence GIQSYCTPPYSVLQDPPQPVV --ligand "COc(cc1)ccc1C#N" --out_dir .  --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise

**Error I got:**

Generating ESM language model embeddings
Processing 1 of 1 batches (1 sequences)
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/insitro2/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ec2-user/miniconda3/envs/insitro2/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ec2-user/software/DiffDock/inference.py", line 71, in <module>
    test_dataset = InferenceDataset(out_dir=args.out_dir, complex_names=complex_name_list, protein_files=protein_path_list,
  File "/home/ec2-user/software/DiffDock/utils/inference_utils.py", line 191, in __init__
    self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}chain{j}'] for j in range(len(s))])
  File "/home/ec2-user/software/DiffDock/utils/inference_utils.py", line 191, in <listcomp>
    self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}chain{j}'] for j in range(len(s))])
KeyError: '1a0qchain0'

**I noticed similar problem was reported in #119 , but I got the same error after I following their solution**

**Comment by aiforbase** [comment]
change
labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))]) 
to
 labels.extend([complex_names[i] + 'chain' + str(j) for j in range(len(s))]) 
 change the code on  line 184

**Comment by aiforbase** [comment]
change code on line 184
 labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
to
 labels.extend([complex_names[i] + 'chain' + str(j) for j in range(len(s))])

**Comment by aiforbase** [comment]
change code on line 184
labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
to
labels.extend([complex_names[i] + 'chain' + str(j) for j in range(len(s))])

**Comment by aiforbase** [comment]
change code on line 184
labels.extend([complex_names[i] + '/_chain_/' + str(j) for j in range(len(s))])
the github comment change '/_chain_/'  to 'chain' ,what's wrong with the comment?

**Comment by aiforbase** [comment]
_chain_

**Comment by aiforbase** [comment]
change code on line 184
to
labels.extend([complex_names[i] + 'chain' + str(j) for j in range(len(s))])

**Comment by pykao** [comment]
@shuhaozhinsitro
It works for me. Thank you for providing the solutions. :)

**Comment by gcorso** [comment]
This issue should be fixed now, apologies, and thank you for raising it!
