### ISSUE TITLE
Fine tuning for the score model

### ISSUE THREAD

**Issue by Xu-kexin** [gcorso/DiffDock#133]
Hi, thank you for creating such a big progress in docking task. I am very interested in your work and am currently working on training the small score model for my research project. I am reaching out to request if it is possible to provide the best trained weights of the small score model, it seems the weight provided is for big score model and confidence model. Due to resource limitations of my GPU, training the large score model is not feasible and training for scratch will take a long time.  I completely respect any limitations or constraints that may prevent you from fulfilling this request. If providing the best trained weights of the small score model is not possible, I will explore alternative options and work towards training the model from scratch within my available resources. I look forward to your response, thank you.

**Comment by gcorso** [comment]
Hi @Xu-kexin you can find [here](https://drive.google.com/file/d/1T54L5QtbgZiGvtpzTpvVIYKagFMWZW1I/view?usp=sharing) an example of a smaller model with similar other hyperparameters we had trained in September

**Comment by Xu-kexin** [comment]
Thank you for the reply @gcorso ! May I ask about the command to run this model?  It seems the command written in readme is not the structure of this model. Thanks again!

**Comment by Xu-kexin** [comment]
I added a new arg named "config_dir" in parsing and edit a bit the train.py. Then I add your yml file directory, it works now! Thank you ^^

**Comment by gcorso** [comment]
I'm glad to managed to fix it!
