### ISSUE TITLE
If I don't want to use torsion, can I just comment out the relevant code? or will there be something wrong with the model?

### ISSUE THREAD

**Issue by ackbar03** [gcorso/DiffDock#142]
Hi, 

I noticed that torsions angles are only modified if model_args.no_torsion is equal to false. 

Since setting this to 'true' in the yaml file leads to errors in loading the model, can I just comment out the relevant code in utils/sampling.py? Or will the prediction then be wrong?

Thanks

**Comment by ackbar03** [comment]
Actually, I just tried this, by commenting out the tor_perturb sections, but the ligand still comes out contorted and different to the initial input. Is there anything else I should be correcting if I don't want the torsion angles to change?

(from line 73 of utils/sampling.py)
```

            # if not model_args.no_torsion:
            #     tor_g = tor_sigma * torch.sqrt(torch.tensor(2 * np.log(model_args.tor_sigma_max / model_args.tor_sigma_min)))
            #     if ode:
            #         tor_perturb = (0.5 * tor_g ** 2 * dt_tor * tor_score.cpu()).numpy()
            #     else:
            #         tor_z = torch.zeros(tor_score.shape) if no_random or (no_final_step_noise and t_idx == inference_steps - 1) \
            #             else torch.normal(mean=0, std=1, size=tor_score.shape)
            #         tor_perturb = (tor_g ** 2 * dt_tor * tor_score.cpu() + tor_g * np.sqrt(dt_tor) * tor_z).numpy()
            #     torsions_per_molecule = tor_perturb.shape[0] // b
            # else:
            #     tor_perturb = None
            tor_perturb = None
            

            # Apply noise
            # new_data_list.extend([modify_conformer(complex_graph, tr_perturb[i:i + 1], rot_perturb[i:i + 1].squeeze(0),
            #                               tor_perturb[i * torsions_per_molecule:(i + 1) * torsions_per_molecule] if not model_args.no_torsion else None)
            #              for i, complex_graph in enumerate(complex_graph_batch.to('cpu').to_data_list())])
            new_data_list.extend([modify_conformer(complex_graph, tr_perturb[i:i + 1], rot_perturb[i:i + 1].squeeze(0),
                                          tor_perturb[i * 0:(i + 1) * 0] if (1==2) else None)
                         for i, complex_graph in enumerate(complex_graph_batch.to('cpu').to_data_list())])
```

**Comment by gcorso** [comment]
Hi @ackbar03 

Yes you can do this, but you also need to avoid that the code sets new RDKit generated structures to start with https://github.com/gcorso/DiffDock/blob/600a23fa23e25d9628840695c8ba55f01111ebff/utils/inference_utils.py#L235 and that the structures are randomizes at the start of inference https://github.com/gcorso/DiffDock/blob/600a23fa23e25d9628840695c8ba55f01111ebff/utils/sampling.py#L15. 

However note that if you are interested in rigid docking of small molecules, training a new model with the --no_torsion parameter will get you better results!

I hope this helps,
Gabriele

**Comment by gcorso** [comment]
Assuming that you are feeding in a path with the molecule in sdf/mol2/pdb form you should be fine with just commenting out lines 235, 236 and 237.

I don't have a recent trained checkpoint for this.

**Comment by ackbar03** [comment]
Noted. 

This seems to work as expected. Thanks very much for your help!
