### ISSUE TITLE
Why do I get close to 0 rmsd for all the compounds I am testing? 

### ISSUE THREAD

**Issue by ackbar03** [gcorso/DiffDock#153]
Hi,

For almost all of the compounds I am testing on, the RMSD is almost close to 0 for all of them, but it is extremely unlikely that this is accurate.

I've checked if it is because the compounds I'm testing are already in the training set. I downloaded the latest version of pdbbind. It is true that for some of the compounds, they are in the training set, but for most of them they are not.

I also want to mention that I am performing diffdock with frozen torsion angles as per issue raised previously: https://github.com/gcorso/DiffDock/issues/142#issue-1807791164
The compounds I am docking are originally obtained from bound co-crystals and separated into two molecules. This is likely to reduce rmsd, but I don't expect it to reduce it to near zero (most of the values are around 0.00xxx). 

Is there any possible explanation for this? Did freezing the torsion angles as per the linked issue somehow remove the randomness used for docking? 

Thanks in advance

**Comment by ackbar03** [comment]
Hi, 

any suggestions as to why this is? I still can't seem to figure out what the problem is. Random initialization at the start seems to be done properly, and the diffusion process looks to be working from the visualization. The results look highly suspicious though.

**Comment by RJ3** [comment]
How are you getting this value "0.00xxx"
The filenames should only have two decimal points, if I recall correctly.

Do you have negative controls in your experiment?

You could also try something like PoseBusters to check the feasibility of the docks - https://posebusters.readthedocs.io/en/latest/

**Comment by ackbar03** [comment]
The numbers reported in your original paper seem much more reasonable. 

Have you also tested with the same compounds, what the results would be if the torsion angles were frozen? Is it possible that most of the errors are actually from incorrect torsion angles, and if it is frozen, it aligns in fact very well?

**Comment by ackbar03** [comment]
My bad, something was wrong with my RMSD calculation
