### ISSUE TITLE
How to change the cache id of confidence model?

### ISSUE THREAD

**Issue by Xu-kexin** [gcorso/DiffDock#164]
Hello, thanks for your work. 
  I saw in the readme you write "run --cache_creation_id 1 then --cache_creation_id 2", but when I use this command "python -m confidence.confidence_train --original_model_dir workdir/small_score_model --run_name confidence_model --inference_steps 20 --samples_per_complex 7 --batch_size 16 --n_epochs 100 --lr 3e-4 --scheduler_patience 50 --ns 24 --nv 6 --num_conv_layers 5 --dynamic_max_cross --scale_by_sigma --dropout 0.1 --all_atoms --remove_hs --c_alpha_max_neighbors 24 --receptor_radius 15 --esm_embeddings_path data/esm2_3billion_embeddings.pt --main_metric loss --main_metric_goal min --best_model_save_frequency 5 --rmsd_classification_cutoff 2 --cache_creation_id 1 --cache_ids_to_combine 1 2 3 4", it throws the exception "ith cache_id do not exist: {cache_id}') # be careful with changing this error message since it is sometimes cought in a try catch Exception: The generated ligand positions with cache_id do not exist: 2".
  I would like to ask about the generation of files in cacheNew/xxx/ligand_positions_idxxx.pkl? (now I saw only the one with id1). Could you give me the way to train the confidence model with cache id more than one? Thank you so much!

**Comment by gcorso** [comment]
Hi, that command should generate the cache with id 1, then when you run with --cache_creation_id 2 it will generate the second... once you have all of them you can run the command and it will start training (they are meant to be run in parallel)

**Comment by Xu-kexin** [comment]
Thank you！
