### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.pdbbind' 

### ISSUE THREAD

**Issue by luwei0917** [gcorso/DiffDock#17]
Thanks for the great work. 

When I do "python -m evaluate --model_dir workdir/paper_score_model --ckpt best_ema_inference_epoch_model.pt --confidence_ckpt best_model_epoch75.pt --confidence_model_dir workdir/paper_confidence_model --run_name DiffDockInference --inference_steps 20 --split_path data/splits/timesplit_test --samples_per_complex 40 --batch_size 10"
I got the following message 
"ModuleNotFoundError: No module named 'datasets.pdbbind' "

I think we need an empty file named "`__init__.py`" under the datasets folder.

**Comment by luwei0917** [comment]
I'm using Python3.8, and on  Ubuntu 20.04.1 LTS.
Relevant post here:
https://stackoverflow.com/questions/448271/what-is-init-py-for

https://stackoverflow.com/questions/70721414/how-does-a-blank-init-py-change-the-behavior-of-import-in-python

some people says it is not needed anymore after python3.3, but I got the error once I removed the init file.

**Comment by gcorso** [comment]
Strange, I would also have said that with recent python distribution it is not needed. Are you sure that the version that the python command is not taking some older distribution in your system?

**Comment by gcorso** [comment]
I will close this issue since from the other one it seems that you have resolved!
Thanks
Gabriele
