### ISSUE TITLE
Strange evaluation results on the PoseBuster set

### ISSUE THREAD

**Issue by LongHung-Pham** [gcorso/DiffDock#187]
Dear the DiffDock team, thank you really much for your efforts in developing the new version. I'm just curious when I ran the new evaluate script of new DiffDock-L **without using the confidence model** on the PoseBuster set, I got quite high results of `top5_rmsds_below_2` (52.47%) and `min_rmsds_below_2` (55.53%) while the result reported from the paper was 50%. I can't figure out why the results were strange, did I miss any crucial step when evaluating?

The checkpoint I used is from https://www.dropbox.com/scl/fi/drg90rst8uhd2633tyou0/diffdock_models.zip?rlkey=afzq4kuqor2jb8adah41ro2lz&dl=1

The command that I ran was
`python -m evaluate --config default_inference_args.yaml --data_dir data/posebusters_benchmark_set --tqdm --dataset posebusters --split_path data/splits/posebusters_benchmark_set_ids.txt --esm_embeddings_path data/posebusters_ESM.pt --num_workers 8 --samples_per_complex 10 --chain_cutoff 10 --batch_size 10 --protein_file protein --ligand_file ligands --model_dir new_ckpt/score_model --confidence_model_dir None --cache_path data/cache1 --save_visualisation`

The results I got was
> Performance without hydrogens included in the loss
> 4 failures due to exceptions
> 0  skipped because complex was not in confidence dataset
> run_times_std 5.12
> run_times_mean 11.29
> mean_rmsd 100.22110042572928
> rmsds_below_2 39.71764705882353
> rmsds_below_5 65.38823529411765
> rmsds_percentile_25 1.16
> rmsds_percentile_50 3.06
> rmsds_percentile_75 6.67
> min_rmsds_below_2 55.529411764705884
> min_rmsds_below_5 81.6470588235294
> mean_centroid nan
> centroid_below_2 61.56
> centroid_below_5 78.26
> centroid_percentile_25 nan
> centroid_percentile_50 nan
> centroid_percentile_75 nan
> top5_self_intersect_fraction 0.0
> top5_rmsds_below_2 52.47
> top5_rmsds_below_5 78.35
> top5_rmsds_percentile_25 0.84
> top5_rmsds_percentile_50 1.81
> top5_rmsds_percentile_75 4.64
> top5_centroid_below_2 61.65
> top5_centroid_below_5 79.76
> top5_centroid_percentile_25 nan
> top5_centroid_percentile_50 nan
> top5_centroid_percentile_75 nan
> top10_self_intersect_fraction 0.0
> top10_rmsds_below_2 55.53
> top10_rmsds_below_5 81.65
> top10_rmsds_percentile_25 0.81
> top10_rmsds_percentile_50 1.6
> top10_rmsds_percentile_75 3.81
> top10_centroid_below_2 61.65
> top10_centroid_below_5 79.76
> top10_centroid_percentile_25 nan
> top10_centroid_percentile_50 nan
> top10_centroid_percentile_75 nan

**Comment by AndChenCM** [comment]
@LongHung-Pham Hi LongHung, were you able to reproduce the results of Diffdock-L on PoseBusters under the default settings? I tried the default settings and the checkpoint in the dropbox on PoseBusters with confidence model, but got rmsds_below_2 about 40%; Meanwhile, about 30 complexes in PoseBusters are skipped. I wonder had you encountered similar problems?
