### ISSUE TITLE
python -m confidence.confidence_train

### ISSUE THREAD

**Issue by yufengwhy** [gcorso/DiffDock#20]
confidence_train.py: error: unrecognized arguments: --inf_sched_alpha 1 --inf_sched_beta 1 --tr_sigma_min 0.1 --tr_sigma_max 34 --rot_sigma_min 0.03 --rot_sigma_max 1.55

**Comment by HannesStark** [comment]
Thanks for pointing out that we still had these unnecessary parameters in the command!
