### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/BindingMOAD_2020_ab_processed_biounit/moad_sequences_new'

### ISSUE THREAD

**Issue by srilekha1993** [gcorso/DiffDock#202]
Hi,
This URL i have referred for  https://zenodo.org/records/10656052 for downloading BindingMOAD_2020_ab_processed dataset. But there is no moad_sequences_new folder inside BindingMOAD_2020_ab_processed. Can anyone please provide the correct link for the above dataset?

**Comment by haotianteng** [comment]
the generated sequence fasta is default `prepared_for_esm.fasta` not `pdbbind_sequences.fasta` in README.md, so should run this command instead:
`python scripts/extract.py esm2_t33_650M_UR50D ${DIFFDOCK_BASE}/data/prepared_for_esm.fasta embeddings_output --repr_layers 33 --include per_tok --truncation_seq_length 4096`

Notice this command should be run at the facebook esm repository, not the DIFFDOCK repository.

README.md needs some correction. @gcorso
