### ISSUE TITLE
a problem with running Graphical UI

### ISSUE THREAD

**Issue by 123sjbsjb** [gcorso/DiffDock#219]
I ran a demo with the first sample(protein:6w70.pdb ligand:6w70_ligand.sdf) in graphical UI. But I ran it without any results and displayed an error message.

Show Error:----------------------------------------------------------------------------------------------------------------------------
[2024-04-26 12:41:32] [run_utils.py:124] INFO - Executing command: python3 inference.py --protein_path=/tmp/gradio/91e785aff143e89f8ac69b9fa79d954d8f9db1e9/6w70.pdb --ligand=/tmp/gradio/791e5fa3bf00a85ff5e9ad67106387c408ec2161/6w70_ligand.sdf --config=/mnt/data/sjb/chem/DiffDock/DiffDock-main/default_inference_args.yaml --no_final_step_noise --samples_per_complex=10 --out_dir=/tmp/tmpz48tjnka
[2024-04-26 12:42:09] [run_utils.py:144] ERROR - Command error:
/home/shijiabao/.conda/envs/diffdock/lib/python3.9/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "

0it [00:00, ?it/s]@> 2143 atoms and 1 coordinate set(s) were parsed in 0.02s.
/mnt/data/sjb/chem/DiffDock/DiffDock-main/datasets/parse_chi.py:91: RuntimeWarning: invalid value encountered in cast
  Y = indices.astype(int)
@> 2143 atoms and 1 coordinate set(s) were parsed in 0.02s.

 1it [00:03,  3.42s/it]
 1it [00:03,  3.42s/it]
-----------------------------------------------------------------------------------------------------------------------------------------

How should I solve this problem？
my package of the conda env:(as per your requirements)
torch                     1.13.1+cu117             pypi_0    pypi
dllogger      version: 1.0.0
e3nn                      0.5.0                    pypi_0    pypi
fair-esm      Version: 2.0.0
networkx                  2.8.4                    pypi_0    pypi
openfold     Version: 2.0.0
pandas                    1.5.1                    pypi_0    pypi
prody                     2.2.0                    pypi_0    pypi
pybind11                  2.11.1                   pypi_0    pypi
rdkit                     2022.3.3                 pypi_0    pypi
scikit-learn              1.1.0                    pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
torch                     1.13.1+cu117             pypi_0    pypi
torch-cluster             1.6.0+pt113cu117          pypi_0    pypi
torch-geometric           2.2.0                    pypi_0    pypi
torch-scatter             2.1.0+pt113cu117          pypi_0    pypi
torch-sparse              0.6.16+pt113cu117          pypi_0    pypi
torch-spline-conv         1.2.1+pt113cu117          pypi_0    pypi
torchmetrics              0.11.0                   pypi_0    pypi
gradio                    3.50.2                   pypi_0    pypi

**Comment by tornikeo** [comment]
It's hard to understand what went wrong like this - can you provide the traceback surrounded in \``` quotes? It's easier to see what went wrong with that.

**Comment by 123sjbsjb** [comment]
> It's hard to understand what went wrong like this - can you provide the traceback surrounded in ``` quotes? It's easier to see what went wrong with that.
I don't know where the error occurred. I kept reporting errors yesterday, but today the project suddenly got through and I didn't make any changes to the code inside.I want to ask a question, how do you understand Rank 1 What about Confidence -0.02? What do the following numbers represent?

**Comment by 123sjbsjb** [comment]
> It's hard to understand what went wrong like this - can you provide the traceback surrounded in ``` quotes? It's easier to see what went wrong with that.

I don't know where the error occurred. I kept reporting errors yesterday, but today the project suddenly got through and I didn't make any changes to the code inside.I want to ask a question, how do you understand Rank 1 What about Confidence -0.02? What do the following numbers represent?
