### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by rczerminski-valo** [gcorso/DiffDock#22]
While going through the steps described in README I am getting an error. See below for the full trace...
[It is on macOS Monterey, Version 12.6 (21G115)]

BTW: It should be
```
python scripts/extract.py esm2_t33_650M_UR50D ../data/pdbbind_sequences.fasta embeddings_output --repr_layers 33 --include per_tok
```

instead of
```
python scripts/extract.py esm2_t33_650M_UR50D data/pdbbind_sequences.fasta embeddings_output --repr_layers 33 --include per_tok
```

Full trace:
```
(diffdock) $ python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings863911206/heterographs.pkl
Number of complexes:  0
/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ryszard/repos/DiffDock/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/Users/ryszard/repos/DiffDock/datasets/pdbbind.py", line 111, in __init__
    print_statistics(self.complex_graphs)
  File "/Users/ryszard/repos/DiffDock/datasets/pdbbind.py", line 361, in print_statistics
    print(f"{name[i]}: mean {np.mean(array)}, std {np.std(array)}, max {np.max(array)}")
  File "<__array_function__ internals>", line 180, in amax
  File "/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/ryszard/miniconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
(diffdock) $
```

**Comment by gcorso** [comment]
Hi @rczerminski-valo,
Sorry for the delay in the answer, from your stack trace you seem to be trying to use a cache that does not contain any complex. What input file did you use? Could you delete the cache and try to rerun the command?
If the problem still occurs I suspect that something wrong is happening during the preprocessing that causes all the complexes that you input to be thrown away, so to understand the issue the output of the preprocessing procedure run in the command (before `loading data from memory`) would be really helpful.

**Comment by rczerminski-valo** [comment]
Hi Gabriele,

For starters, I am just trying to follow the steps described in the [README](https://github.com/gcorso/DiffDock#readme) file 

> What input file did you use?

```data/protein_ligand_example_csv.csv```

> Could you delete the cache and try to rerun the command?

Removing cache (i.e. `rm -rf data/cache_torsion/`) followed by `python -m inference ...` results in similar error >> [inference.1.log](https://github.com/gcorso/DiffDock/files/9852146/inference.1.log) <<

> so to understand the issue the output of the preprocessing procedure run in the command (before loading data from memory) would be really helpful.

Do you mean output from 
`python ../datasets/esm_embedding_preparation.py --protein_ligand_csv data/protein_ligand_example_csv.csv --out_file data/prepared_for_esm.fasta`
run?

**Comment by gcorso** [comment]
Hi @rczerminski-valo,
Thanks for the update, the log file is really helpful. From those you can see that for all the complexes in the preprocessing it outputs the following message:
```
Skipping data/PDBBind_processed/6mo8/6mo8_protein_processed.pdb____data/PDBBind_processed/6mo8/6mo8_ligand.sdf because of the error:
Encountered valid chain id that was not present in the LM embeddings
```
So it seems that the issue lies with the ESM embeddings not being present or in the correct location. Are you sure that you have generated the ESM embeddings file and that it is in the location indicated by the `--esm_embeddings_path` argument in the inference command?

**Comment by rczerminski-valo** [comment]
I tried to go step by step following README, but now I am getting into trouble even sooner. I have appended the file with my logs. At your convenience, if you could take a look what am I doing wrong I would appreciate it very much.
File `LOGS_RCZ/README`  contains a record of the commands I have executed.
[LOGS_RCZ.tgz](https://github.com/gcorso/DiffDock/files/9924504/LOGS_RCZ.tgz)

**Comment by GsGithub17** [comment]
Hi all,

I have the same problem. Is this problem resolved yet?

Here is the error I run into. 

Thank! 

loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings398919913/heterographs.pkl

Number of complexes:  0

/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.

  return _methods._mean(a, axis=axis, dtype=dtype,

/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars

  ret = ret.dtype.type(ret / rcount)

/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice

  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide

  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',

/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars

  ret = ret.dtype.type(ret / rcount)

Traceback (most recent call last):

  File "/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/media/sf_D_DRIVE/DiffDock/inference.py", line 81, in <module>

    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,

  File "/media/sf_D_DRIVE/DiffDock/datasets/pdbbind.py", line 111, in __init__

    print_statistics(self.complex_graphs)

  File "/media/sf_D_DRIVE/DiffDock/datasets/pdbbind.py", line 376, in print_statistics

    print(f"{name[i]}: mean {np.mean(array)}, std {np.std(array)}, max {np.max(array)}")

  File "<__array_function__ internals>", line 180, in amax

  File "/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2793, in amax

    return _wrapreduction(a, np.maximum, 'max', axis, None, out,

  File "/home/gemechis/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction

    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by alpha-beta-user** [comment]
> ```
> Skipping data/PDBBind_processed/6mo8/6mo8_protein_processed.pdb____data/PDBBind_processed/6mo8/6mo8_ligand.sdf because of the error:
> Encountered valid chain id that was not present in the LM embeddings
> ```
> 
> So it seems that the issue lies with the ESM embeddings not being present or in the correct location. Are you sure that you have generated the ESM embeddings file and that it is in the location indicated by the `--esm_embeddings_path` argument in the inference command?
Hi, I have got this problem too. For your answers, do you mean that I need to generate ESM2 Beddings correctly. I want know that at the last step of ESM2 Bedding Generate, is it downding a lagre file (about 2GB)。
Thank you for your reply

**Comment by HannesStark** [comment]
@rczerminski-valo 
Are you sure that the directory 6mo8 exists in your PDBBind_processed directory?
From your log file this does not seem to be the case.

Regarding your point that "It should be"

```python scripts/extract.py esm2_t33_650M_UR50D ../data/pdbbind_sequences.fasta embeddings_output --repr_layers 33 --include per_tok```
instead of

```python scripts/extract.py esm2_t33_650M_UR50D data/pdbbind_sequences.fasta embeddings_output --repr_layers 33 --include per_tok```


I think this is not actually the case and you should run into problems when running it like this since the embeddings_output directory is then created in the wrong directory.
You would have to run the original command in the parent directory of where you ran it.
