### ISSUE TITLE
error while running the inference example

### ISSUE THREAD

**Issue by velocirraptor23** [gcorso/DiffDock#223]
Hi,
I am running this as the example:
python -m inference --config default_inference_args.yaml --protein_ligand_csv data/protein_ligand_example.csv --out_dir results/
Before I was able to run it completely but I reinstalled the things becuase I messed up the enviroment and now I am getting this error. Not sure what that means.
  File "/cluster/ddu/cmmartinez001/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/ddu/cmmartinez001/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/ddu/cmmartinez001/DiffDock/inference.py", line 41, in <module>
    resource.setrlimit(resource.RLIMIT_NOFILE, (64000, rlimit[1]))
ValueError: current limit exceeds maximum limit

Any help would be highly appreciated.

BW,

Cesar

**Comment by velocirraptor23** [comment]
I change the number to 4000, it did the emebedings with ESM but the I got another error:
Generating ESM language model embeddings
Processing 1 of 1 batches (4 sequences)
0it [00:00, ?it/s]Segmentation fault

Not sure at this poinr what happened. Also wondering what that number means and why decreasing it allowed me to run the code.

BW,

Cesar

**Comment by jsilter** [comment]
Generally a segmentation fault means the computer ran out of memory. So you may need better hardware. We also have a huggingface space available: https://huggingface.co/spaces/reginabarzilaygroup/DiffDock-Web

**Comment by velocirraptor23** [comment]
but it was working first. dont understand what has changed. Is that cache memory? Or a new update has made something more heavy in terms of memory?
