### ISSUE TITLE
Systematically different results from web server and local version

### ISSUE THREAD

**Issue by mapuyi** [gcorso/DiffDock#243]
I tried single runs from local installed version and also from the web server, and I got totally different behaviors of ligand poses even though I used exactly the same input files. I understand that every run should produce slightly different results, but the difference between local version and web server is obviously systematic that the local version gave ligand poses all around the protein while the web server gave most poses in the nearly accurate position. 

I did not add any customized settings or "hack" into the backend script to change anything. I just followed the basic instructions and made it run. Is there any differences between web server and local version at the first place?

**Comment by ZengweiKOU** [comment]
I also have the same issue.
Beside, I also have a problem: WARNING -Complex XXX Batch 1 Interfence Iteration XX smaple failed.

**Comment by mapuyi** [comment]
> I also have the same issue. Beside, I also have a problem: WARNING -Complex XXX Batch 1 Interfence Iteration XX smaple failed.

That happens to me occasionally and I'm not sure why. Rerun several more times and this warning just doesn't show up anymore.

I have also noticed that

**Comment by mapuyi** [comment]
I have also noticed that in the docker container and web server I always meet this warning: **parse_chi.py:91: RuntimeWarning: invalid value encountered in cast Y = indices.astype(int)**, but the results seem fine and most of the poses are in the nearly correct positions.

However in the local conda environment running, I never see this warning and always get terrible poses for the same input complex.

I have followed the default settings all the time. I also manually checked the scripts from docker container and did not find anything different.

**Comment by ZengweiKOU** [comment]
> I have also noticed that in the docker container and web server I always meet this warning: **parse_chi.py:91: RuntimeWarning: invalid value encountered in cast Y = indices.astype(int)**, but the results seem fine and most of the poses are in the nearly correct positions.
> 
> However in the local conda environment running, I never see this warning and always get terrible poses for the same input complex.
> 
> I have followed the default settings all the time. I also manually checked the scripts from docker container and did not find anything different.

Thanks

**Comment by mapuyi** [comment]
Update here:

I re-installed all the packages under my local conda environment and this time I strictly followed the version numbers of them according to the authors' environment file (torch==1.13.1+cu117, torch_cluster===1.6.0+pt113cu117, and so on... all of them). Good news is now I can finally get similar results as Docker's and web-server's. It seems that some of those dependencies/packages have some sort of  implicit impacts on the outputs.

**Comment by jsilter** [comment]
There's a reason we specify all of those version numbers. Informally I have observed the same as you, the results absolutely can change based on the library. I would generally expect the effect to be similar to picking a different random seed (assuming nothing breaks) but it isn't tested.

**Comment by starwingc** [comment]
I encounter the similar problem, and it seems to be solved by mainting the same version of 
```
     - e3nn==0.5.1
    - networkx==2.8.4
    - pandas==1.5.1
    - pybind11==2.11.1
    - pytorch-lightning==1.9.5
    - rdkit==2022.03.3
    - scikit-learn==1.1.0
    - torchmetrics==0.11.0
    ```

I install the pytorch and pyg of cuda 12.4, and they are fine, I don't need openfold  and didn't istall it since I don't provide a sequence, also the only difference is 
```
- fair-esm[esmfold]==2.0.1
```

But the results are fine and looks like what webserver gives me, hope this can provide an reference.
