### ISSUE TITLE
Traceback (most recent call last):   Error

### ISSUE THREAD

**Issue by min0210** [gcorso/DiffDock#245]
Traceback (most recent call last):
  File "/home/sangmin/apps/docking/DiffDock-1.1.2/inference.py", line 324, in <module>
    main(_args)
  File "/home/sangmin/apps/docking/DiffDock-1.1.2/inference.py", line 143, in main
    raise Exception(f"Models not found locally and failed to download them from {remote_urls}")
Exception: Models not found locally and failed to download them from ['https://github.com/gcorso/DiffDock/releases/latest/download/diffdock_models.zip', 'https://github.com/gcorso/DiffDock/releases/download/v1.1/diffdock_models.zip']

When these problems occur, where to fix them?

This is my command line:
/home/sangmin/anaconda3/envs/diffdock/bin/python3 /home/sangmin/apps/docking/DiffDock-1.1.2/inference.py 
--config /home/sangmin/apps/docking/DiffDock-1.1.2/default_inference_args.yaml 
--protein_ligand_csv /home/sangmin/project/classification/dataset/DUDE/aa2ar/diffdock/input.csv 
--out_dir /home/sangmin/project/classification/dataset/DUDE/aa2ar/diffdock/result

Thanks.

**Comment by ShuoAndy** [comment]
you can download it on https://github.com/gcorso/DiffDock/releases/download/v1.1/diffdock_models.zip

**Comment by min0210** [comment]
thanks!
