### ISSUE TITLE
Regarding the issue of the input file

### ISSUE THREAD

**Issue by ZhuLvs** [gcorso/DiffDock#251]
Dear DiffDock authors,

Thank you for providing such a powerful tool!

I am currently working on a protein design project where each residue of the generated proteins only contains the initial four atoms: CA, N, O, and C.

I would like to ask if I need to repair the side chains and hydrogen atoms in my PDB file using a tool like PDBFixer when docking ligands with DiffDock. Will the side chains and hydrogen atoms significantly affect the docking results and accuracy?

**Comment by jsilter** [comment]
You don't need hydrogen atoms in the ligand or protein. However you do need the side chain positions.
