### ISSUE TITLE
RuntimeError: invalid value in pickle

### ISSUE THREAD

**Issue by ShuoAndy** [gcorso/DiffDock#253]
I followed the default data preprocessing procedure in the original code and stored the pdbbind dataset in the form of a heterogeneous graph. However, when I read the heterogeneous graph file heterographs10.pkl, the following error occurred (as far as I know, this should correspond to the 1000 complexes data from 10000 to 11000 in the training set):

```
Traceback (most recent call last):
  File "/data3/wangjs/workspace/DiffDock/train.py", line 227, in <module>
    main_function()
  File "/data3/wangjs/workspace/DiffDock/train.py", line 181, in main_function
    train_loader, val_loader, val_dataset2 = construct_loader(args, t_to_sigma, device)
  File "/data3/wangjs/workspace/DiffDock/datasets/loader.py", line 83, in construct_loader
    train_dataset = PDBBind(cache_path=args.cache_path, split_path=args.split_train, keep_original=True,
  File "/data3/wangjs/workspace/DiffDock/datasets/pdbbind.py", line 189, in __init__
    self.complex_graphs, self.rdkit_ligands = self.collect_all_complexes()
  File "/data3/wangjs/workspace/DiffDock/datasets/pdbbind.py", line 366, in collect_all_complexes
    l = pickle.load(f)
RuntimeError: invalid value in pickle
```

It seems that the pkl file is completely corrupted, but I haven't been able to identify which complex or which part of the code caused this corruption.

Other heterogeneous graph files, such as heterographs9.pkl from pdbbind dataset, did not have this problem. After deleting heterographs10.pkl, I successfully reproduced the experimental results in your paper. I would like to know what happened and if there is a solution to this issue.

**Comment by echen1214** [comment]
I found that this RuntimeError occurred when trying to load rdkit_ligand10.pkl and that ligand in 3q4c was the cause. After excluding the preprocessing of 3q4c, I was able to run the DiffDock training

**Comment by ShuoAndy** [comment]
I will try it later, thank you very much!


-----原始邮件-----
发件人:"Eric Chen" ***@***.***>
发送时间:2024-11-09 02:06:52 (星期六)
收件人: gcorso/DiffDock ***@***.***>
抄送: "A.硕" ***@***.***>, Author ***@***.***>
主题: Re: [gcorso/DiffDock] RuntimeError: invalid value in pickle (Issue #253)






I found that this RuntimeError occurred when trying to load rdkit_ligand10.pkl and that ligand in 3q4c was the cause. After excluding the preprocessing of 3q4c, I was able to run the DiffDock training

**Comment by harini-vijayshankar** [comment]
I ran into the same issue, and I can confirm that it was resolved on excluding 3q4c.
