### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by suneelbvs** [gcorso/DiffDock#31]
Hi,

Is there anyway, we can generate animation (.gif) of the predicted results?. Thanks in advance.

**Comment by HannesStark** [comment]
There indeed is a very simple way to do so!

You can activate the flag `--save_visualisation` when running inference. This produces pdb files with frames of all reverse diffusion steps. You can then open these in PyMol and render a video such as a gif.

Please feel free to reopen the issue if that does not clarify everything!
