### ISSUE TITLE
Explicit valence for atom # 48 H, 4, is greater than permitted

### ISSUE THREAD

**Issue by ZixuanFeng-NYU** [gcorso/DiffDock#32]
Exception: ('RDKit could not read the molecule ', 'data/3d_sdf/1eby_01.sdf')
Explicit valence for atom # 48 H, 4, is greater than permitted
could not process mol

**Comment by gcorso** [comment]
Hi @ZixuanFeng-NYU 
It seems there is an issue in the sdf file you are trying to give as input, it is hard for us to give you any further indication on top of what is already contained in the Exception without access to file or other further detail.

**Comment by gcorso** [comment]
I will close the issue for inactivity, please reopen it if the problem persists
