### ISSUE TITLE
ESM embeddings script missing ligand option

### ISSUE THREAD

**Issue by jadolfbr** [gcorso/DiffDock#39]
Docs state that you don't need a csv and can use `--ligand` but this is not the case
```
optional arguments:
  -h, --help            show this help message and exit
  --out_file OUT_FILE
  --protein_ligand_csv PROTEIN_LIGAND_CSV
                        Path to a .csv specifying the input as described in the main README
  --protein_path PROTEIN_PATH
                        Path to a single PDB file. If this is not None then it will be used instead of the --protein_ligand_csv
```

**Comment by HannesStark** [comment]
Hi Jared,

The ESM embeddings are only created for the protein. For that reason, there is no ligand option in the ESM embeddings script. You can safely run everything without providing any ligand to this script. 

If you provide a protein ligand csv, then only the protein paths in that csv will be used.
