### ISSUE TITLE
If you want to benchmark the virtual-screening power

### ISSUE THREAD

**Issue by UnixJunkie** [gcorso/DiffDock#4]
LIT-PCBA: An Unbiased Data Set for Machine Learning and Virtual Screening
https://pubs.acs.org/doi/10.1021/acs.jcim.0c00155

Dataset:
https://drugdesign.unistra.fr/LIT-PCBA/

**Comment by gcorso** [comment]
Why would this dataset be more suited than PDBBind to evaluate the capacity to perform docking?

**Comment by UnixJunkie** [comment]
As far as I know, PDBBind is about binding energy or so. It does not tell you anything about the virtual screening power of a method.

**Comment by gcorso** [comment]
Well, PDBBind also gives binding energy, but we are not even interested in that at the moment. We are evaluating the quality of our method to dock the ligand in the correct pose. How to use this to do virtual screening is a whole other research question that has been studied for decades with existing effective solutions, but that we have not yet tackled directly.
