### ISSUE TITLE
Existing ligand from PDB

### ISSUE THREAD

**Issue by abmukho** [gcorso/DiffDock#41]
Is there a way to include existing ligand in a PDB structure and dock a new ligand. This is necessary to block off the pocket pertaining to the originally bound ligand in the protein PDB.
An example is an ATP/GTP bound pocket which is inaccessible to a second ligand that we would try to dock using diffdock.
If not, is it possible to dock more than one ligand simultaneously to the protein.

**Comment by NiklasTR** [comment]
Hi @abmukho - I think an easy way (if it is just one structure you are interested in) is to manually remove the ligand with a tool like PyMol before using diffdock.

**Comment by abmukho** [comment]
Hi @NiklasTR Thanks for the prompt response. Perhaps I was not very clear with the question. To rephrase what I've said earlier, we would like to do blind docking of a ligand (L2) of interest to a protein where one or more of the high propensity pocket is already bound with non-protein small molecules (L1). Is it possible to have the context of L1 (I understand that ESM embedding only works with proteins) while running the docking experiment for L2.

L2 docking Protein+L1 resulting in an output of Protein +L1+L2.

**Comment by abmukho** [comment]
What I notice is that if I rip out L1 from the protein, L2 binds to the same pocket as the one for L1. But this is not permissible in reality. L2 should be aware of L1 blocking the L1 pocket.

**Comment by gcorso** [comment]
Hi @abmukho, this functionality is indeed not present in the current version of DiffDock. Hopefully, we will add it in future versions! Thanks for raising your interest!
