### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Dedock** [gcorso/DiffDock#42]
Hi, I followed all the installation steps.
Tried to run the inference script, but receive just `Segmentation fault`
Can you help me to understand what I did wrong or what is the issue?
![image](https://user-images.githubusercontent.com/20503942/200546924-4bcbfbd6-106a-4208-826c-d40c96363036.png)

**Comment by ballaneypranav** [comment]
This happened with me to an issue with pytorch libraries. Try running this:
```python -c 'import torch_geometric'```
and see if you get the error again.

If yes, install `pyg` and `pytorch-spline-conv` using Conda instead of pip. (instructions [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
