### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by xuzhang5788** [gcorso/DiffDock#44]
Thanks for your repo. When I followed your readme and tried to create a conda env using "conda env create", I got 
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]

failed

CondaEnvException: Pip failed

**Comment by HannesStark** [comment]
Unfortunately, I have never seen this problem.
I would recommend making a fresh conda environment with python and then installing all the packages with pip manually to potentially avoid this issue.

**Comment by Jnelen** [comment]
Hi there,

I had the exact same problem when trying to install DiffDock. 
I think the problem was that pip was trying to get the pytorch geometric (pyg) packages from an incompatible source. Luckily there is an easy fix: remove the torch-* packages from the environment.yml, and install it again using `conda env create.` After that you, activate your diffdock environment and run this command:
`conda install pyg -c pyg`
Alternatively you can also use pip and run:
`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html`

This worked for me, and hopefully it also works for you!

**Comment by HannesStark** [comment]
There are also new conda environment setup instructions in the readme now!

**Comment by xuzhang5788** [comment]
@HannesStark 
Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked. 

$conda env create.
$conda activate diffdock
$conda install pyg -c pyg
$python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas

Just in case someone needs it.

**Comment by Jnelen** [comment]
Glad to hear I could help! Maybe an easy solution for everyone could be to specify the pyg channel in the environment.yml?
Something like this: https://pastebin.com/f4e0Hcj8 
I just copied the latest environment.yml, removed the pytorch-cluster, geometric, scatter, sparse and spline-conv lines from the list, and added the -pyg::pyg line (I used the :: to specify the installation from the pyg channel)
I just tried it out by installing from the environment.yml (`conda env create` ). It finished without any installation errors, and it seems to work just fine.

**Comment by marissadolorfino** [comment]
@Jnelen I followed those instructions but still get the segmentation fault error, though I previously had Diffdock running properly. Any tips on how to debug?

**Comment by Jnelen** [comment]
> @Jnelen I followed those instructions but still get the segmentation fault error, though I previously had Diffdock running properly. Any tips on how to debug?

Hi there @marissadolorfino!
I tried the following steps, and this is working for me, hopefully it can work for you aswell!

`conda create --name diffdock python=3.9 pytorch==1.11.0 pytorch-cuda=11.7 -c pytorch -c nvidia`
`conda activate diffdock`
`conda install pyg -c pyg`
`python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas`
`pip install "fair-esm[esmfold]"`
`pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'`
`pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git'`

Kind regards,
Jochem

**Comment by asarigun** [comment]
> @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> 
> $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> 
> Just in case someone needs it.

I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:

```bash
conda create --name diffdock_new2 python=3.9
conda activate diffdock_new
export CUDA_PATH=/usr/local/cuda-12.1
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
export PATH=${PATH}:/usr/local/cuda-12.1/bin
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
pip install "fair-esm[esmfold]"
pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
conda install pyg -c pyg
```

Then run the command for inference as indicated in README:

```bash
python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
````

**Comment by Jnelen** [comment]
> > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > Just in case someone needs it.
> 
> I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> 
> ```shell
> conda create --name diffdock python=3.9
> conda activate diffdock
> export CUDA_PATH=/usr/local/cuda-12.1
> export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> export PATH=${PATH}:/usr/local/cuda-12.1/bin
> conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> pip install "fair-esm[esmfold]"
> pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> conda install pyg -c pyg
> ```
> 
> Then run the command for inference as indicated in README:
> 
> ```shell
> python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> ```

Hi there!

I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.

**Comment by asarigun** [comment]
> > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > Just in case someone needs it.
> > 
> > 
> > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > ```shell
> > conda create --name diffdock python=3.9
> > conda activate diffdock
> > export CUDA_PATH=/usr/local/cuda-12.1
> > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > pip install "fair-esm[esmfold]"
> > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > conda install pyg -c pyg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then run the command for inference as indicated in README:
> > ```shell
> > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > ```
> 
> Hi there!
> 
> I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.

Hi @Jnelen,

This is something I definitely was looking for! Thanks for the code and letting me know.

Best,

Ahmet

**Comment by Jnelen** [comment]
> > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > Just in case someone needs it.
> > > 
> > > 
> > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > ```shell
> > > conda create --name diffdock python=3.9
> > > conda activate diffdock
> > > export CUDA_PATH=/usr/local/cuda-12.1
> > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > pip install "fair-esm[esmfold]"
> > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > conda install pyg -c pyg
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then run the command for inference as indicated in README:
> > > ```shell
> > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > ```
> > 
> > 
> > Hi there!
> > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> 
> Hi @Jnelen,
> 
> This is something I definitely was looking for! Thanks for the code and letting me know.
> 
> Best,
> 
> Ahmet

Awesome!
If you have any questions or run into any problems, don't hesitate to reach out!

Kind regards,
Jochem

**Comment by Yang-Wang-2020** [comment]
Followed Jnelen's post but still get the following error when running the test command:
OSError: /home/y/miniconda3/envs/diffdock_2/lib/python3.9/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev

**Comment by Jnelen** [comment]
> > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > Just in case someone needs it.
> > > 
> > > 
> > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > ```shell
> > > conda create --name diffdock python=3.9
> > > conda activate diffdock
> > > export CUDA_PATH=/usr/local/cuda-12.1
> > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > pip install "fair-esm[esmfold]"
> > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > conda install pyg -c pyg
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then run the command for inference as indicated in README:
> > > ```shell
> > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > ```
> > 
> > 
> > Hi there!
> > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> 
> Thanks for making this! I still couldn't make the GPU version work. "sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification" Could you please share an example config file for slurm?

Hi there!

Does the queue you are launching your jobs to have GPU resources? I think this could be the problem if that's not the case. Could you otherwise provide more details of what you're doing (or trying to do)? Since this is about DiffDockHPC however, maybe it's better to discuss it on that GitHub page? Or if you want to keep it private you can also reach out to me at jnelen@ucam.edu.

Final note I wanted to make is that DiffDockHPC currently isn't updated to DiffDock-L/DiffDock V1.1. It should still work just fine, but it still uses "regular" DiffDock V1.0!

**Comment by Yang-Wang-2020** [comment]
> > > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > Just in case someone needs it.
> > > > 
> > > > 
> > > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > > ```shell
> > > > conda create --name diffdock python=3.9
> > > > conda activate diffdock
> > > > export CUDA_PATH=/usr/local/cuda-12.1
> > > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > pip install "fair-esm[esmfold]"
> > > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > > conda install pyg -c pyg
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Then run the command for inference as indicated in README:
> > > > ```shell
> > > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > > ```
> > > 
> > > 
> > > Hi there!
> > > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> > 
> > 
> > Thanks for making this! I still couldn't make the GPU version work. "sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification" Could you please share an example config file for slurm?
> 
> Hi there!
> 
> Does the queue you are launching your jobs to have GPU resources? I think this could be the problem if that's not the case. Could you otherwise provide more details of what you're doing (or trying to do)? Since this is about DiffDockHPC however, maybe it's better to discuss it on that GitHub page? Or if you want to keep it private you can also reach out to me at [jnelen@ucam.edu](mailto:jnelen@ucam.edu).
> 
> Final note I wanted to make is that DiffDockHPC currently isn't updated to DiffDock-L/DiffDock V1.1. It should still work just fine, but it still uses "regular" DiffDock V1.0!

I couldn't find the issue page under the DiffDockHPC repo.

**Comment by Jnelen** [comment]
> > > > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > > Just in case someone needs it.
> > > > > 
> > > > > 
> > > > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > > > ```shell
> > > > > conda create --name diffdock python=3.9
> > > > > conda activate diffdock
> > > > > export CUDA_PATH=/usr/local/cuda-12.1
> > > > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > pip install "fair-esm[esmfold]"
> > > > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > > > conda install pyg -c pyg
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Then run the command for inference as indicated in README:
> > > > > ```shell
> > > > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > > > ```
> > > > 
> > > > 
> > > > Hi there!
> > > > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> > > 
> > > 
> > > Thanks for making this! I still couldn't make the GPU version work. "sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification" Could you please share an example config file for slurm?
> > 
> > 
> > Hi there!
> > Does the queue you are launching your jobs to have GPU resources? I think this could be the problem if that's not the case. Could you otherwise provide more details of what you're doing (or trying to do)? Since this is about DiffDockHPC however, maybe it's better to discuss it on that GitHub page? Or if you want to keep it private you can also reach out to me at [jnelen@ucam.edu](mailto:jnelen@ucam.edu).
> > Final note I wanted to make is that DiffDockHPC currently isn't updated to DiffDock-L/DiffDock V1.1. It should still work just fine, but it still uses "regular" DiffDock V1.0!
> 
> I couldn't find the issue page under the DiffDockHPC repo.

Oops, my bad, it should be there now!

**Comment by Jnelen** [comment]
> > > > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > > Just in case someone needs it.
> > > > > 
> > > > > 
> > > > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > > > ```shell
> > > > > conda create --name diffdock python=3.9
> > > > > conda activate diffdock
> > > > > export CUDA_PATH=/usr/local/cuda-12.1
> > > > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > pip install "fair-esm[esmfold]"
> > > > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > > > conda install pyg -c pyg
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Then run the command for inference as indicated in README:
> > > > > ```shell
> > > > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > > > ```
> > > > 
> > > > 
> > > > Hi there!
> > > > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> > > 
> > > 
> > > Thanks for making this! I still couldn't make the GPU version work. "sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification" Could you please share an example config file for slurm?
> > 
> > 
> > Hi there!
> > Does the queue you are launching your jobs to have GPU resources? I think this could be the problem if that's not the case. Could you otherwise provide more details of what you're doing (or trying to do)? Since this is about DiffDockHPC however, maybe it's better to discuss it on that GitHub page? Or if you want to keep it private you can also reach out to me at [jnelen@ucam.edu](mailto:jnelen@ucam.edu).
> > Final note I wanted to make is that DiffDockHPC currently isn't updated to DiffDock-L/DiffDock V1.1. It should still work just fine, but it still uses "regular" DiffDock V1.0!
> 
> I couldn't find the issue page under the DiffDockHPC repo.

@Yang-Wang-2020 did you manage to fix the issue already? I also just pushed an update to DiffDockHPC which allows you to get around slurm (--no_slurm). I'm also working on updating my fork to support DiffDock v1.1 (DiffDock-L). I hope to get it finished either this week or the next!

**Comment by Yang-Wang-2020** [comment]
> > > > > > > @HannesStark Thank you for your update on the new conda env. It works on Ubuntu 20.04. However, after I upgraded my Ubuntu to 22.04, when I ran inference.py, I got "Segmentation fault (core dumped)". Then I used @Jnelen's method to reinstall diffdock, It finally worked.
> > > > > > > $conda env create. $conda activate diffdock $conda install pyg -c pyg $python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > > > Just in case someone needs it.
> > > > > > 
> > > > > > 
> > > > > > I also got `Segmentation fault (core dumped)` error with Ubuntu 22.04. Here's how I solved the issue:
> > > > > > ```shell
> > > > > > conda create --name diffdock python=3.9
> > > > > > conda activate diffdock
> > > > > > export CUDA_PATH=/usr/local/cuda-12.1
> > > > > > export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64
> > > > > > export PATH=${PATH}:/usr/local/cuda-12.1/bin
> > > > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
> > > > > > pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
> > > > > > python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
> > > > > > pip install "fair-esm[esmfold]"
> > > > > > pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
> > > > > > pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
> > > > > > conda install pyg -c pyg
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Then run the command for inference as indicated in README:
> > > > > > ```shell
> > > > > > python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Hi there!
> > > > > I'm very happy to hear my solution worked for you! Another option you could have tried is to use DiffDock using Singularity. I made a fork of DiffDock ([DiffDockHPC](https://github.com/Jnelen/DiffDockHPC)), which includes a Singularity image that makes DiffDock work on basically any system running Singularity. It also makes it easy to run many DiffDock calculations in parallel (using Slurm as a job manager), which is very useful when you want to run it on a HPC-cluster for example.
> > > > 
> > > > 
> > > > Thanks for making this! I still couldn't make the GPU version work. "sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification" Could you please share an example config file for slurm?
> > > 
> > > 
> > > Hi there!
> > > Does the queue you are launching your jobs to have GPU resources? I think this could be the problem if that's not the case. Could you otherwise provide more details of what you're doing (or trying to do)? Since this is about DiffDockHPC however, maybe it's better to discuss it on that GitHub page? Or if you want to keep it private you can also reach out to me at [jnelen@ucam.edu](mailto:jnelen@ucam.edu).
> > > Final note I wanted to make is that DiffDockHPC currently isn't updated to DiffDock-L/DiffDock V1.1. It should still work just fine, but it still uses "regular" DiffDock V1.0!
> > 
> > 
> > I couldn't find the issue page under the DiffDockHPC repo.
> 
> @Yang-Wang-2020 did you manage to fix the issue already? I also just pushed an update to DiffDockHPC which allows you to get around slurm (--no_slurm). I'm also working on updating my fork to support DiffDock v1.1 (DiffDock-L). I hope to get it finished either this week or the next!

I have managed to get the CPU version working, but I still can't make it run on GPU. Thank you so much for helping with this. Let's move the conversation to the DiffDockHPC repo. Couldn't wait to try the --no_slurm version.
