### ISSUE TITLE
ESM bedding   Problem

### ISSUE THREAD

**Issue by alpha-beta-user** [gcorso/DiffDock#45]
When I follow the readme, in the following step
(diffdock) icer@ubuntu:~/my_prj/diffdock/DiffDock$ HOME=esm/model_weights python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt" to esm/model_weights/.cache/torch/hub/checkpoints/esm2_t33_650M_UR50D.pt

I found it is still here, can not continue.

**Comment by alpha-beta-user** [comment]
I find it is downloading a large file, maybe need a long time

**Comment by HannesStark** [comment]
This command is indeed downloading the weights of the ESM model which are required for generating the language model embeddings
