### ISSUE TITLE
0it [00:00, ?it/s]Killed

### ISSUE THREAD

**Issue by alpha-beta-user** [gcorso/DiffDock#49]
Hi, When I run the inference, There exists a kill error, No other explanations is offered. So I do not know where to debug.Thank you for your time. Here is my log file.
`~/my_prj/diffdock/DiffDock$ python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 2 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings492466589/heterographs.pkl
Number of complexes:  5
radius protein: mean 29.789531707763672, std 12.012960433959961, max 53.81545639038086
radius molecule: mean 6.223214149475098, std 3.113785982131958, max 12.253068923950195
distance protein-mol: mean 65.75000762939453, std 19.175703048706055, max 76.23456573486328
rmsd matching: mean 0.0, std 0.0, max 0
HAPPENING | confidence model uses different type of graphs than the score model. Loading (or creating if not existing) the data for the confidence model now.
loading data from memory:  data/cache_torsion_allatoms/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_atomRad5_atomMax8_esmEmbeddings492466589/heterographs.pkl
Number of complexes:  5
radius protein: mean 29.789531707763672, std 12.012960433959961, max 53.81545639038086
radius molecule: mean 6.45449686050415, std 3.5746219158172607, max 13.436868667602539
distance protein-mol: mean 65.57249450683594, std 19.06147575378418, max 75.89845275878906
rmsd matching: mean 0.0, std 0.0, max 0
common t schedule [1.  0.5]
Size of test dataset:  5
**0it [00:00, ?it/s]Killed**
`

**Comment by HannesStark** [comment]
This sounds to me like a system specific issue where the execution environment stops the process from running.
I am not sure we can help debug this, but please reopen the issue if you think otherwise and have additional information!
