### ISSUE TITLE
Zenodo dataset processing?

### ISSUE THREAD

**Issue by MatthewMasters** [gcorso/DiffDock#50]
The Zenodo dataset proteins are different from the original PDBBind. Can you explain how these were processed? I did not see any details in the paper or code.

Thanks!

**Comment by lonngxiang** [comment]
The Zenodo dataset link  doesn't work  in china, please Add an alternate download site if possible; e.g. Google Cloud Disk

**Comment by moziya** [comment]
The same question, could you please explain what kinds of processing have been done for the proteins before docking? Or that would be better if you could share the script/tool to process them. Thank you!

**Comment by HannesStark** [comment]
We use the preprocessed PDBBind data of the EquiBind paper. This includes preprocessing the protein with Open Babel and then with the "reduce"(https://github.com/rlabduke/reduce) library to add missing hydrogens, correct hydrogens, and correctly flip histidines. 

Additionally, the proteins in the dataset on Zenodo from EquiBind only contain the chains that have an atom within 10Å of a ligand atom. The baselines are also tested under this setting.
Please reopen the issue if questions remain!

**Comment by kuku609** [comment]
> We use the preprocessed PDBBind data of the EquiBind paper. This includes preprocessing the protein with Open Babel and then with the "reduce"(https://github.com/rlabduke/reduce) library to add missing hydrogens, correct hydrogens, and correctly flip histidines.
> 
> Additionally, the proteins in the dataset on Zenodo from EquiBind only contain the chains that have an atom within 10Å of a ligand atom. The baselines are also tested under this setting. Please reopen the issue if questions remain!

Can you tell me how you preprocess proteins using Open Babel? Do the preprocessing steps alter the conformation of the complex? Thank you very much.
