### ISSUE TITLE
I am not sure if I got the right results after I run inference

### ISSUE THREAD

**Issue by xuzhang5788** [gcorso/DiffDock#51]
$python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise

Precomputing and saving to cache SO(3) distribution table
Precomputing and saving to cache torus distribution table
100%|█████████████████████████████████████████| 201/201 [00:45<00:00,  4.39it/s]
100%|█████████████████████████████████████████| 201/201 [00:55<00:00,  3.59it/s]
/home/xzhang/projects/DiffDock/utils/torus.py:39: RuntimeWarning: invalid value encountered in divide
  score_ = grad(x, sigma[:, None], N=100) / p_
Reading molecules and generating local structures with RDKit (unless --keep_local_structures is turned on).
0it [00:00, ?it/s]rdkit coords could not be generated without using random coords. using random coords now.
6it [00:01,  3.74it/s]
Reading language model embeddings.
Generating graphs for ligands and proteins
loading complexes: 100%|██████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings863911206/heterographs.pkl
Number of complexes:  6
radius protein: mean 33.793853759765625, std 14.15740966796875, max 53.81545639038086
radius molecule: mean 6.548925876617432, std 3.7833714485168457, max 14.822683334350586
distance protein-mol: mean 59.33454513549805, std 22.522035598754883, max 75.89938354492188
rmsd matching: mean 0.0, std 0.0, max 0
HAPPENING | confidence model uses different type of graphs than the score model. Loading (or creating if not existing) the data for the confidence model now.
Reading molecules and generating local structures with RDKit (unless --keep_local_structures is turned on).
0it [00:00, ?it/s]rdkit coords could not be generated without using random coords. using random coords now.
6it [00:01,  3.53it/s]
Reading language model embeddings.
Generating graphs for ligands and proteins
loading complexes: 100%|██████████████████████████| 6/6 [00:02<00:00,  2.82it/s]
loading data from memory:  data/cache_torsion_allatoms/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_atomRad5_atomMax8_esmEmbeddings863911206/heterographs.pkl
Number of complexes:  6
radius protein: mean 33.793853759765625, std 14.15740966796875, max 53.81545639038086
radius molecule: mean 6.218267917633057, std 2.776658773422241, max 12.076842308044434
distance protein-mol: mean 58.96320724487305, std 22.422767639160156, max 75.24571990966797
rmsd matching: mean 0.0, std 0.0, max 0
common t schedule [1.   0.95 0.9  0.85 0.8  0.75 0.7  0.65 0.6  0.55 0.5  0.45 0.4  0.35
 0.3  0.25 0.2  0.15 0.1  0.05]
Size of test dataset:  6
0it [00:00, ?it/s]/home/xzhang/miniconda3/envs/diffdock/lib/python3.9/site-packages/e3nn/o3/_spherical_harmonics.py:82: UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
To report the issue, try enable logging via setting the envvariable ` export PYTORCH_JIT_LOG_LEVEL=manager.cpp`
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809662/work/torch/csrc/jit/codegen/cuda/manager.cpp:237.)
  sh = _spherical_harmonics(self._lmax, x[..., 0], x[..., 1], x[..., 2])
5it [03:45, 30.19s/it]Failed on ['data/PDBBind_processed/6mo8/6mo8_protein_processed.pdb____data/PDBBind_processed/6hld/6hld_ligand.mol2'] Invariant Violation
	no eligible neighbors for chiral center
	Violation occurred on line 213 in file Code/GraphMol/FileParsers/MolFileStereochem.cpp
	Failed Expression: nbrScores.size()
	RDKIT: 2022.09.1
	BOOST: 1_78

6it [04:24, 44.08s/it]
Failed for 1 complexes
Skipped 0 complexes
Results are in results/user_predictions_small

There is only one file in folder "index5_data-PDBBind_processed-6mo8-6mo8_protein_processed.pdb____data-PDBBind_processed-6hld-6hld_ligand.mol2", but there are 41 files in the other 5 folders. Did I run the inference correctly? Thanks

**Comment by wjxts** [comment]
I had the same output and I think it failed.

**Comment by gcorso** [comment]
Based on the output it seems to have run successfully for 5 complexes and failed for 1. 
The error on the one that failed is equal to the one reported in https://github.com/gcorso/DiffDock/issues/56 however I am still not sure about the cause of this
