### ISSUE TITLE
Strange ligand's pose output  

### ISSUE THREAD

**Issue by PhungVanDuy** [gcorso/DiffDock#6]
Thank you for the great project.

I have tried to dock histamine h1 receptor (protein) with diphenhydramine (ligand) but I got a strange pose of the ligand. 
This file is complex after docking. 
[H1_diphenhydramine_DiffDock.pdb.zip](https://github.com/gcorso/DiffDock/files/9720538/H1_diphenhydramine_DiffDock.pdb.zip)
After that, I tried to use Schrodinger to visualize more details output and I got this one
![image](https://user-images.githubusercontent.com/28798474/194198338-4d444752-0fc4-4278-9b6f-108da64fa837.png)
The problem is the ligand is completely deformed, and the original ligand is no longer visible (as you can see in the image above).
Do you have any comments/suggestions to solve this problem?

**Comment by HannesStark** [comment]
Hi!
Could you also send the ligand and receptor files that you used as input to DiffDock?

**Comment by PhungVanDuy** [comment]
> Hi! Could you also send the ligand and receptor files that you used as input to DiffDock?

Thank you for your response. This file contain ligand and receptor: 
[sample_diffdoc.zip](https://github.com/gcorso/DiffDock/files/9725470/sample_diffdoc.zip)

**Comment by HannesStark** [comment]
These are the results I get when running your input:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/32128654/194341959-c6c219af-bbf8-41fc-9e99-d12a901051ac.png">

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/32128654/194342364-be4640d7-e3a3-4133-9669-80f9f90ee152.png">


[results.zip](https://github.com/gcorso/DiffDock/files/9725756/results.zip)

**Comment by PhungVanDuy** [comment]
> These are the results I get when running your input. I also attached the files of the result. Maybe the viewer that you are using is messing up the connectivity of the molecular graph.
> 
> <img alt="image" width="1179" src="https://user-images.githubusercontent.com/32128654/194341959-c6c219af-bbf8-41fc-9e99-d12a901051ac.png">
> 
> <img alt="image" width="1785" src="https://user-images.githubusercontent.com/32128654/194342790-adcbb642-e873-4202-87d9-ee6e0c474d17.png">
> 
> [results.zip](https://github.com/gcorso/DiffDock/files/9725756/results.zip)

@HannesStark  Thank you for your great response. Your output same as mine, but when we send this output to our chemical expert who used Glide to analyze the problem is the same. So it seems DiffDock, and EquiBind is focusing on determining whether to dock or not and preliminary about the position that docked help for virtual screening. So when we are interested in the interaction of protein and atom in molecular in detail. It seems current algorithms are still not supported yet, anyway I am not a chemical expert just tried to convey the problem that our chemical scientist discussed to you.

**Comment by gcorso** [comment]
Hi @PhungVanDuy, thanks for you comment.
If I understand correctly you are saying that it would be useful for the model to also output the residues or protein atoms that the different parts of the ligand interact with. Indeed this is not yet supported by our method although I expect that something like this could be easily added to the confidence model output, however, it would require some non-ambiguous way of defining when two elements are interacting or some expert labels of this on part of PBDBind.

**Comment by PhungVanDuy** [comment]
> Hi @PhungVanDuy, thanks for you comment. If I understand correctly you are saying that it would be useful for the model to also output the residues or protein atoms that the different parts of the ligand interact with. Indeed this is not yet supported by our method although I expect that something like this could be easily added to the confidence model output, however, it would require some non-ambiguous way of defining when two elements are interacting or some expert labels of this on part of PBDBind.

Yes, I totally agree with you on the technical aspect. Thank you so much for the great discussion. 
btw, did you try to use GINA to get an affinity score,... to evaluate your model? If yes, can you share about it?

**Comment by gcorso** [comment]
Hi, no we did not try to use any existing model on top of our method to predict affinity. However, I expect them not to work very well out of the box and without any relaxation. How to best use DiffDock for affinity prediction is a very interesting question that we are actively exploring!
