### ISSUE TITLE
Is diffdock only for monomeric protein?

### ISSUE THREAD

**Issue by ZixuanFeng-NYU** [gcorso/DiffDock#64]
AssertionError: Found duplicate sequence labels

**Comment by gcorso** [comment]
To clarify by monomeric do you mean single chain proteins? If so the answer is definitely no, e.g. approx 1/3 of PDBBind contains is formed by receptors with multiple chains.
Regarding the error, could you provide more context?

**Comment by ZixuanFeng-NYU** [comment]
This error happens when I wanted to generated embeddings for proteins, some of my protein have duplicates of same sequences (homomeric), I am not sure whether this is the issue causing the error

**Comment by ZixuanFeng-NYU** [comment]
And I check some example of homomeric proteins in PDB website, they were processed to be in monomeric state in extracted protein_processed data prepared in diffdock testsets

**Comment by mwisniewskidrugdesign** [comment]
Hi, how was this problem solved?
