### ISSUE TITLE
`rec_max_radius` and `receptor_radius` difference

### ISSUE THREAD

**Issue by vtarasv** [gcorso/DiffDock#70]
`rec_max_radius` argument in both `TensorProductScoreModel.__init__` methods is set to `30` by default and the default value is used in the models' architecture generation:
https://github.com/gcorso/DiffDock/blob/fff8f0b5eb98a49980553096fdd283c27f8cf022/models/all_atom_score_model.py#L14-L20
https://github.com/gcorso/DiffDock/blob/fff8f0b5eb98a49980553096fdd283c27f8cf022/models/score_model.py#L92-L98

However, I noticed that the actual distance threshold defined by `receptor_radius` and used in residue-level protein graph generation is set to 15:
https://github.com/gcorso/DiffDock/blob/fff8f0b5eb98a49980553096fdd283c27f8cf022/workdir/paper_score_model/model_parameters.yml#L55
https://github.com/gcorso/DiffDock/blob/fff8f0b5eb98a49980553096fdd283c27f8cf022/workdir/paper_confidence_model/model_parameters.yml#L54

I wonder if this is intentional difference or just a minor mistake?

**Comment by gcorso** [comment]
Hi @vtarasv,
Thanks for pointing this out!
The rec_max_radius parameter is used to generate the embedding of the distance length, therefore it does not need to be necessarily the same as the radius cutoff (although it should not be smaller). But you are right, setting them to be the same would have probably been a small optimization in the way the distance embedding vector is used. However, this should not be changed after the model is trained as it would change the reference used to compute the distances.
