### ISSUE TITLE
`self.odd_parity` not defined in `TensorProductScoreModel` (`all_atom_score_model.py`)

### ISSUE THREAD

**Issue by murthyn** [gcorso/DiffDock#76]
In `all_atom_score_model.py`, `self.odd_parity` is referenced:
```
class TensorProductScoreModel(torch.nn.Module):
    def __init__(...):
                ...
                self.tor_final_layer = nn.Sequential(
                    nn.Linear(2 * ns if not self.odd_parity else ns, ns, bias=False),
                    nn.Tanh(),
                    nn.Dropout(dropout),
                    nn.Linear(ns, 1, bias=False)
                )
```
However, `self.odd_parity` is not defined in `TensorProductScoreModel`, causing an `AttributeError`.

Seems like the solution is just to define `self.odd_parity` in `__init__` and modify `utils.py::get_model` to set the odd parity from the `args`? Or to just to remove the `self.odd_parity == True` case since all configs in the repo seem to set it to `False`?

**Comment by murthyn** [comment]
Can spin up a small PR if that sounds corrrect!

**Comment by gcorso** [comment]
Thanks for rasing the issue, it should be fixed now!
