### ISSUE TITLE
Masking to prevent binding at given pocket. 

### ISSUE THREAD

**Issue by maclandrol** [gcorso/DiffDock#79]
Hello @gcorso and team ! 

Thanks for the awesome work. I was wondering if you have thought about enabling "blocking a site" to prevent binding to it, as opposed to restricting prediction to a specific site ?

I am interested into looking into it, but would appreciate if you can give some pointers about the fastest way to achieve that with the current code. 

Best !

**Comment by gcorso** [comment]
Hi @maclandrol, 
The most obvious way is to simply sample more and reject a sample if it comes inside the pocket. A more principled way is to add a repulsion term to the translational score that, during inference, keeps you away from the given site (I can maybe elaborate in an email).
