### ISSUE TITLE
Retrain the confidence model

### ISSUE THREAD

**Issue by ShuqiLu** [gcorso/DiffDock#80]
I want to train a confidence model  and I use the following commands:

python -m confidence.confidence_train --original_model_dir ./workdir/paper_score_model --ckpt best_ema_inference_epoch_model --run_name confidence_model --inference_steps 20 --samples_per_complex 7 --batch_size 16 --n_epochs 100 --lr 3e-4 --scheduler_patience 50 --ns 24 --nv 6 --num_conv_layers 5 --dynamic_max_cross --scale_by_sigma --dropout 0.1 --all_atoms --remove_hs --c_alpha_max_neighbors 24 --receptor_radius 15 --esm_embeddings_path data/esm2_3billion_embeddings.pt --main_metric loss --main_metric_goal min --best_model_save_frequency 5 --rmsd_classification_cutoff 2 --cache_creation_id 1 --cache_ids_to_combine 1 2 3 4.

But I got the following errors:
FileNotFoundError: [Errno 2] No such file or directory: '/data/rsg/nlp/hstark/ligbind/data/cacheNew_torsion/limit0_INDEXtimesplit_no_lig_overlap_train_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings/heterographs.pkl'

Can you give me the scripts to generate the data files like the heterographs.pkl?

**Comment by lonngxiang** [comment]
> I want to train a confidence model and I use the following commands:
> 
> python -m confidence.confidence_train --original_model_dir ./workdir/paper_score_model --ckpt best_ema_inference_epoch_model --run_name confidence_model --inference_steps 20 --samples_per_complex 7 --batch_size 16 --n_epochs 100 --lr 3e-4 --scheduler_patience 50 --ns 24 --nv 6 --num_conv_layers 5 --dynamic_max_cross --scale_by_sigma --dropout 0.1 --all_atoms --remove_hs --c_alpha_max_neighbors 24 --receptor_radius 15 --esm_embeddings_path data/esm2_3billion_embeddings.pt --main_metric loss --main_metric_goal min --best_model_save_frequency 5 --rmsd_classification_cutoff 2 --cache_creation_id 1 --cache_ids_to_combine 1 2 3 4.
> 
> But I got the following errors: FileNotFoundError: [Errno 2] No such file or directory: '/data/rsg/nlp/hstark/ligbind/data/cacheNew_torsion/limit0_INDEXtimesplit_no_lig_overlap_train_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings/heterographs.pkl'
> 
> Can you give me the scripts to generate the data files like the heterographs.pkl?

have you succeed train a score model？

**Comment by gcorso** [comment]
Hi @ShuqiLu,
This was due to an absolute path set in the score model parameters, now it should work. 
If you still get some error run (the start of) the score model training command to generate the cache that can be used by the score model to generate the samples for the confidence model (just the preprocessing). 
Then the confidence model should be able to run smoothly using that data.

Sorry for the inconvenience!
