### ISSUE TITLE
version pytorch

### ISSUE THREAD

**Issue by MachineGUN001** [gcorso/DiffDock#81]
Please ask if you can support the upgrade 1.8 version pytorch, because after the upgrade pytorch should be able to support many amd GPU chips, so that more people can have the opportunity to can apply GPU for computing. The pytorch currently configured in the environment should be 1.13.1, which did not support most AMD GPU chips .
many thanks

**Comment by HannesStark** [comment]
Everything should work with pytorch 1.8. 
We recommend trying to use the pytorch version you need. Feel free to reopen the issue if it persists.
