### ISSUE TITLE
Question about output irreps

### ISSUE THREAD

**Issue by dylanabramson33** [gcorso/DiffDock#83]
If I understand correctly the output rotation and translation scores are 2 vectors of even and odd parity (1 even and 1 odd for both) created here https://github.com/gcorso/DiffDock/blob/3829a23af8ba1971de63fa523361369f0b066a07/models/score_model.py#L200 These are then added together to get 1 vector translations and 1 for rotations. I thought you would just need the odd parity components for both translations and rotations so I was wondering why the even parity part is included?

**Comment by gcorso** [comment]
There would be exact odd parity if one would consider a full atomic model, but since we remove atoms/coarse grain both on the receptor (only consider C-alpha atoms) and ligand (only heavy atoms) the coarse-grained energy is no longer parity invariant

**Comment by dylanabramson33** [comment]
got it, thanks!
