### ISSUE TITLE
File not found when python datasets/pdbbind_lm_embedding_preparation.py

### ISSUE THREAD

**Issue by Alain-chavanieu** [gcorso/DiffDock#84]
Hello 

Iam following instructions to set up env and running on your complexes. We ll write a jupyter notebook based on the google colab. So far, all good.

However, i tried also the Retraining DiffDock section. Probleme the zip file seems incomplete.
I did step by step (see attached file if needed). However when i reached :
python datasets/pdbbind_lm_embedding_preparation.py
 it appears that the directory 1a50 is empty (i tried to download twice the zip) (see below)

Than you for your help

python datasets/pdbbind_lm_embedding_preparation.py
  0%|                                        | 31/19120 [00:03<31:44, 10.02it/s]
Traceback (most recent call last):
  File "datasets/pdbbind_lm_embedding_preparation.py", line 63, in <module>
    structure = biopython_parser.get_structure('random_id', rec_path)
  File "/disk/prog/anaconda/envs/diffdock/lib/python3.8/site-packages/Bio/PDB/PDBParser.py", line 96, in get_structure
    with as_handle(file) as handle:
  File "/disk/prog/anaconda/envs/diffdock/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/disk/prog/anaconda/envs/diffdock/lib/python3.8/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'data/PDBBind_processed/1a50/1a50_protein.pdb'

**Comment by gcorso** [comment]
Strange, maybe you could just skip that (by simply putting a Exception handler and just skip that training complex?! 
It should not affect the final training significantly

**Comment by HannesStark** [comment]
Closing this issue since it seems to be resolved based on the time passed. Feel free to reopen if this is incorrect.
