### ISSUE TITLE
Providing protein structure alignment code

### ISSUE THREAD

**Issue by AustinApple** [gcorso/DiffDock#89]
Hello, Thank you all for your wonderful work on DiffDock. Could you provide the code for aligning protein structures generated by ESMFold to crystal ones?

Thanks

**Comment by gcorso** [comment]
Hi @AustinApple 

Apologies for the delay in reply! You can find it [here](https://github.com/gcorso/DiffDock/blob/main/data/apo_alignment.ipynb).

I hope this helps,
Gabriele
