### ISSUE TITLE
Is pretraining torsion model useful for docking?

### ISSUE THREAD

**Issue by yufengwhy** [gcorso/DiffDock#9]
The code of 'datasets.geom' is used for pretraining?  

https://anonymous.4open.science/r/DiffDock/datasets/pdbbind.py 

from datasets.geom import GeomNoiseTransform, Geom

**Comment by gcorso** [comment]
Hi, yes we did some tests on that but did not give any improvement. 
This repo contains all the code in this repo is all that is necessary to reproduce the best results we got

**Comment by yufengwhy** [comment]
> Hi, yes we did some tests on that but did not give any improvement. This repo contains all the code in this repo is all that is necessary to reproduce the best results we got

Could you kindly provide `datasets.geom`? which is missing in the code base. 

The pretraining did not give any improvement is only for torsion? Maybe we could add transition and rotation?

**Comment by gcorso** [comment]
Please contact me by email and I'll share the datasets.geom file. Yes it is only for torsion because the GEOM datasets only provides molecular conformers, that therefore do not have an associated relative translation and rotation to a protein.
