### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by ydzdfci** [gcorso/DiffDock#90]
File "/DiffDock/utils/inference_utils.py", line 184, in <listcomp>

> labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])

File "/DiffDock/utils/inference_utils.py", line 192, in <listcomp>
    

> self.lm_embeddings.append([lm_embeddings[complex_names[i] + '_chain_' + str(j)] for j in range(len(s))])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

I'm running python 3.8 and got this error when trying to run testset_csv.csv.
Then I changed this line to 
    

> labels.extend([f'{complex_names[i]}_chain_{j}' for j in range(len(s))])
self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}_chain_{j}'] for j in range(len(s))])

and then it worked.

**Comment by JuLieAlgebra** [comment]
I have exactly the same issue for `testset_csv.csv` as well! Thank you so much for the fix that worked for you.

**Comment by HannesStark** [comment]
Thanks we fixed it!

**Comment by CihanSoylu** [comment]
https://github.com/gcorso/DiffDock/blob/main/utils/inference_utils.py#L184 and https://github.com/gcorso/DiffDock/blob/main/utils/inference_utils.py#L191 are causing a key error now. 

Changing 191 to 

                self.lm_embeddings.append([lm_embeddings[f'{complex_names[i]}_chain_{j}'] for j in range(len(s))])

fixes the error.
