### ISSUE TITLE
problem about the o3.FullyConnectedTensorProduct

### ISSUE THREAD

**Issue by alpha-beta-user** [gcorso/DiffDock#91]
Hello, I am confused about the code:
` self.tp = tp = o3.FullyConnectedTensorProduct(in_irreps, sh_irreps, out_irreps, shared_weights=False)`

I have also check the e3nn document, but I can not understand it. Maybe the theory is diffcult for me. I also try to debug into this function and its forward computation.  I also get a trouble. so can you list some examples about its computation process, such as a data input, what kinds of computation need to be done.

Thanks a lot!

**Comment by gcorso** [comment]
Hi @alpha-beta-user 

To best understand it I suggest looking at this series of videos https://www.youtube.com/watch?v=q9EwZsHY1sk&list=PLx3xbphkO3qIlBoESkbafXaDtr0tq5iRd

**Comment by alpha-beta-user** [comment]
> Hi @alpha-beta-user
> 
> To best understand it I suggest looking at this series of videos https://www.youtube.com/watch?v=q9EwZsHY1sk&list=PLx3xbphkO3qIlBoESkbafXaDtr0tq5iRd

Thank you for your reply
