### ISSUE TITLE
error with example file

### ISSUE THREAD

**Issue by ydzdfci** [gcorso/DiffDock#92]
I followed installation instructions in readme and make a conda environment.
When I tried to run 
python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
I got error message "OSError: anaconda3/envs/dd/lib/python3.8/site-packages/torch_sparse/_diag_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb"
This is the steps I used
git clone https://github.com/gcorso/DiffDock.git
conda create --name diffdock python=3.8
conda activate diffdock
conda install pytorch pytorch-cuda=11.7 -c pytorch -c nvidia
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
python -m pip install PyYAML scipy "networkx[default]" biopython rdkit-pypi e3nn spyrmsd pandas biopandas
pip install "fair-esm[esmfold]"
pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'

This is the package list in environment:
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
biopandas                 0.4.1                    pypi_0    pypi
biopython                 1.81                     pypi_0    pypi
blas                      1.0                         mkl
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
deepspeed                 0.5.9                    pypi_0    pypi
dllogger                  1.0.0                    pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
e3nn                      0.5.1                    pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
fair-esm                  2.0.0                    pypi_0    pypi
filelock                  3.10.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.39.0                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0                 pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py38h793c122_1    conda-forge
hjson                     3.1.0                    pypi_0    pypi
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                      pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.0.0         h9e868ea_25371
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.0.25                      0    nvidia
libcurand                 10.3.2.56                     0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.9.0                hd6dc26d_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnsl                    2.0.0                h7f98852_0    conda-forge
libnvjpeg                 11.8.0.2                      0    nvidia
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               hca2bb57_3    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lightning-utilities       0.8.0                    pypi_0    pypi
markupsafe                2.1.2            py38h1de0b5d_0    conda-forge
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2023.0.0         h6d00ec8_25399
ml-collections            0.1.1                    pypi_0    pypi
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
openfold                  1.0.0                    pypi_0    pypi
openssl                   3.1.0                h0b41bf4_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
opt-einsum-fx             0.1.4                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
psutil                    5.9.4                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.16          he550d4f_1_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      3_cp38    conda-forge
pytorch                   2.0.0           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-lightning         2.0.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.7.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rdkit-pypi                2022.9.5                 pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
spyrmsd                   0.5.2                    pypi_0    pypi
sympy                     1.11.1           py38h578d9bd_2    conda-forge
tbb                       2021.8.0             hf52228f_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
torch-cluster             1.6.1+pt113cu117          pypi_0    pypi
torch-geometric           2.2.0                    pypi_0    pypi
torch-scatter             2.1.1+pt113cu117          pypi_0    pypi
torch-sparse              0.6.17+pt113cu117          pypi_0    pypi
torch-spline-conv         1.2.2+pt113cu117          pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
triton                    1.0.0                    pypi_0    pypi
typing_extensions         4.5.0              pyha770c72_0    conda-forge
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge

**Comment by gcorso** [comment]
Hi @ydzdfci, the underlying issue seems to be some environment conflicts/errors with torch_sparse but I can't really help with how to solve it, I suggest trying to raise a similar issue on the torch_space repository

**Comment by HannesStark** [comment]
Closing this issue since it seems to be resolved based on the time passed. Feel free to reopen if this is incorrect.
