### ISSUE TITLE
CUDA and PyTorch versions mismatch

### ISSUE THREAD

**Issue by HongjianLi** [gcorso/DiffDock#94]
Hi,
  While I was installing OpenFold, which is one of the dependencies of DiffDock, the following error occurred:

`RuntimeError: The detected CUDA version (12.0) mismatches the version that was used to compile PyTorch (11.6). Please make sure to use the same CUDA versions.`

  The cuda toolkit installed on my server is version 12.0.140, and I have no privilege to downgrade it to v11. How can I proceed to compile and run DiffDock?

**Comment by gcorso** [comment]
Hi, I suggest creating a new conda environment and installing pytorch first by selecting on the [PyTorch website](https://pytorch.org/) the correct version for your device and then install the rest of the dependencies

**Comment by HannesStark** [comment]
Closing this issue since it seems to be resolved based on the time passed. Feel free to reopen if this is incorrect.
