### ISSUE TITLE
Getting binding affinity from DiffDock output

### ISSUE THREAD

**Issue by dhruv-acog** [gcorso/DiffDock#95]
Hi, do you have a method to get the binding affinity of a protein-ligand complex using DiffDock output poses?

**Comment by gcorso** [comment]
Hi @dhruv-acog 

No, at the moment DiffDock does not compute binding affinities. This will hopefully be added in future versions. 
However, we (and collaborators) have observed positive correlation between the confidence score given by DiffDock (to the first or first few poses) and the binding affinity. This correlation can be made even stronger by combining DiffDock's score with traditional docking scoring functions (e.g. Vina or GNINA).

I hope this helps!
