### ISSUE TITLE
dataset was removed from Zenodo, where to download the dataset?

### ISSUE THREAD

**Issue by Joeklepko** [gcorso/DiffDock#98]
I'm trying to download the dataset from Zenodo, it shows below:
      The record you are trying to access was removed from Zenodo. The metadata of the record is kept for archival purposes.
      Reason for removal: Spam record, removed by Zenodo staff.
where can I download now? thx

**Comment by Joeklepko** [comment]
I'm using this link:
https://zenodo.org/record/6408497

**Comment by HannesStark** [comment]
Apparently, it was accidentally automatically removed.
It is back up now. (Maybe you need to delete browser cache to see it)

**Comment by zhaisilong** [comment]
Thank you a lot, i solved this problem on safari by removing the web cache of zenodo.
